apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tls-secret
  namespace: {{ .Values.namespace }}
spec:
  secretName: tls-secret
  issuerRef:
    name: letsencrypt-{{ .Values.certEnvironment }}
  commonName: {{ .Values.dnsName }}
  dnsNames:
  - {{ .Values.dnsName }}
