{{ if .Values.backendTag }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: roster-backend
  name: roster-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: roster-backend
  template:
    metadata:
      labels:
        app: roster-backend
    spec:
      containers:
      - name: backend
        image: {{ .Values.backendImage }}:{{ .Values.backendTag }}
        env:
        - name: STORAGE_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: storage
              key: CONNECTION_STRING
        imagePullPolicy: Always
        ports:
        - containerPort: 3501
          protocol: TCP

{{ end }}