{{ if .Values.frontendTag }}

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: roster-frontend
  name: roster-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: roster-frontend
  template:
    metadata:
      labels:
        app: roster-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontendImage }}:{{ .Values.frontendTag }}
        env:
        imagePullPolicy: Always
        ports:
        - containerPort: 3500
          protocol: TCP
{{ end }}