apiVersion: v1
kind: Service
metadata:
  name: roster-backend-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: roster-backend
  ports:
  - protocol: TCP
    port: 3501
    targetPort: 3501
  type: ClusterIP
